#on: ["push"]  
# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:
  push:
  #  tags:
   # - 'v*'
    branches:
    - main
    paths:
    - 'CalcuSub/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

  test:
    uses: tsiswaryalakshmi/nuget5sep/.github/workflows/Template.yml@main
    with:
      PATH: CalcuSub\CalculationRef.nuspec
      NUGET_SOURCE_URL: https://nuget.pkg.github.com/tsiswaryalakshmi/index.json
     # PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
    secrets:
      NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }} 
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }} 
